DROP TABLE Movie_Location;
DROP TABLE Movie_Genre;
DROP TABLE User_Tagged_Movie;
DROP TABLE User_Rated_Movie;
DROP TABLE Movie_Tag;
DROP TABLE Movie_Actor;
DROP TABLE Tag;
DROP TABLE Movie;
DROP TABLE Person;